UPDATE article SET DESIGNATION = LCASE(DESIGNATION);
UPDATE article SET DESIGNATION = UCASE(DESIGNATION) WHERE PRIX>10;
UPDATE article SET DESIGNATION = LCASE(DESIGNATION) WHERE ID=2;
UPDATE article,fournisseur SET PRIX = PRIX*1.1 WHERE ID_FOU=fournisseur.ID AND fournisseur.NOM="FDM SA";